Proyecto/Proyecto/Models/bebidas.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.Spatial;
namespace Proyecto.Models
{
    public partial class bebidas
    {
        [Key]
        public int idbebida { get; set; }
        [Required(ErrorMessage = "Completa este campo")]

        [StringLength(100)]
        public string nombre { get; set; }

        [StringLength(255)]
        public string foto { get; set; }

        [Required(ErrorMessage = "Completa este campo")]
        [DataType(DataType.MultilineText)]
        public string ingredientes { get; set; }

        [Required(ErrorMessage = "Completa este campo")]
        [DataType(DataType.MultilineText)] 
        public string preparacion { get; set; }

        [StringLength(128)]
        public string idusuario { get; set; }

        
        [StringLength(256)]
        public string usuario { get; set; }  
    }
}

Proyecto/Proyecto/Controllers/bebidasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Proyecto.Models;
using Microsoft.AspNet.Identity;
using System.Web.UI.WebControls;
using System.IO;
using PagedList;

namespace Proyecto.Controllers
{

    public class bebidasController : Controller
    {
        private bproyecto db = new bproyecto();

        // GET: bebidas
         public ActionResult Index( int page=1)
          {
              return View(db.bebidas.OrderByDescending(v => v.idbebida).ToPagedList(page,8));
          }

        

        public ActionResult buscarbebida(string palabra)
        {

            if (!String.IsNullOrEmpty(palabra))
            {
                return View(db.bebidas.Where(x => x.nombre.Contains(palabra)).ToList());
            }
            return View(db.bebidas.ToList());
        }

        public ActionResult misbebidas()
        {
            return View(db.bebidas.ToList());
        }

        // GET: bebidas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            bebidas bebidas = db.bebidas.Find(id);
            if (bebidas == null)
            {
                return HttpNotFound();
            }
            return View(bebidas);
        }

        // GET: bebidas/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }
        [Authorize]
        // POST: bebidas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idbebida,nombre,usuario,idusuario,foto,ingredientes,preparacion")] bebidas bebidas)
        {
            if (ModelState.IsValid)
            {
                bebidas.usuario=User.Identity.GetUserName();
                db.bebidas.Add(bebidas);
                db.SaveChanges();
                return RedirectToAction("Index");
                
            } 
            return View(bebidas);
        }
        


        // GET: bebidas/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            bebidas bebidas = db.bebidas.Find(id);

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            
            if (bebidas == null)
            {
                return HttpNotFound();
            }
            return View(bebidas);
        }

        // POST: bebidas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idbebida,nombre,usuario,idusuario,foto,ingredientes,preparacion")] bebidas bebidas)
        { 
            if (ModelState.IsValid)
            {
                db.Entry(bebidas).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(bebidas);
        }


        private const string direccion= "~/Fotos/";
         

        // GET: bebidas/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            bebidas bebidas = db.bebidas.Find(id);
            if (bebidas == null)
            {
                return HttpNotFound();
            }
            return View(bebidas);
        }

        // POST: bebidas/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            bebidas bebidas = db.bebidas.Find(id);
            db.bebidas.Remove(bebidas);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult FileUploadUpdate(HttpPostedFileBase file)
        {
            int id = Convert.ToInt16(Request.Form["idbebida"]);
            bproyecto db = new bproyecto();

            //Consulta para retomar y cambiar informacion de artista
            var query = from ord in db.bebidas where ord.idbebida == id select ord;
            foreach (bebidas ord in query)
            {
                ord.nombre = Request.Form["nombre"]; 
                ord.ingredientes = Request.Form["ingredientes"];
                ord.preparacion = Request.Form["preparacion"];
                ord.idbebida = Convert.ToInt16(Request.Form["idbebida"]);
                ord.idusuario = Request.Form["idusuario"];
                string oldFoto = ord.foto;

                if (file != null)
                {
                    string ImageName = System.IO.Path.GetFileName(file.FileName);
                    ord.foto = ImageName;
                    //Eliminar foto
                    if (System.IO.File.Exists(Server.MapPath("~/Fotos/" + oldFoto)))
                    {
                        System.IO.File.Delete(oldFoto);
                    }
                    string physicalPath = Server.MapPath("~/Fotos/" + ImageName);
                    // save image in folder
                    file.SaveAs(physicalPath);

                }
            }
            try
            {
                //save new record in database
                db.SaveChanges();
            }
            catch (Exception e)
            {
            }

            //Display records
            return RedirectToAction("Index");
        }

 

        //subir imagen en el Create
        public ActionResult FileUpload(HttpPostedFileBase file)
        {

            if (file != null)
            {
                bproyecto db = new bproyecto();
                string ImageName = System.IO.Path.GetFileName(file.FileName);
                string physicalPath = Server.MapPath("~/Fotos/" + ImageName);

                // save image in folder
                file.SaveAs(physicalPath);

                //save new record in database
                bebidas newRecord = new  bebidas();
                newRecord.nombre = Request.Form["nombre"];
                newRecord.ingredientes = Request.Form["ingredientes"];
                newRecord.preparacion = Request.Form["preparacion"];
                newRecord.idbebida = Convert.ToInt16(Request.Form["idbebida"]);
                newRecord.idusuario = Request.Form["idusuario"];
                newRecord.usuario = User.Identity.GetUserName();
                newRecord.foto = ImageName;
                db.bebidas.Add(newRecord);
                db.SaveChanges();

            } 
            //Display records
            return RedirectToAction("misbebidas");
        }

       

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Proyecto/Proyecto/Views/bebidas/Create.cshtml
@model Proyecto.Models.bebidas

@{
    ViewBag.Title = "Crear";
}
	
<h2>Crea un nuevo trago</h2>

<div class="row">
    <div class="col-md-6">
        <br />
        @using (Html.BeginForm("FileUpload", "bebidas", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.foto, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input type="file" name="file" id="file" style="width: 100%;" /> <br />
                        @Html.ValidationMessageFor(model => model.foto, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ingredientes, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ingredientes, new { htmlAttributes = new { @class = "form-control", rows="6" } })
                        @Html.ValidationMessageFor(model => model.ingredientes, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.preparacion, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.preparacion, new { htmlAttributes = new { @class = "form-control", rows="6" } })
                        @Html.ValidationMessageFor(model => model.preparacion, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Crear" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }
    </div>
        <div class="col-md-6" style="text-align:justify;">
            <h3 style="text-align:center;">Ayudanos a mantener un orden</h3>
            <h4>Los ingredientes separalos por comas, guiones, asteriscos o cualquier otro tipo de caracter.<br /><br />
            Procura no escribir una gran explicacion de como preparar el trago.<br /><br />
            Gracias por ayudarnos :)</h4>
        </div>
   
</div>

<div>
    @Html.ActionLink("Regresar a la lista", "misbebidas", null, new { @class = "btn btn-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Proyecto/Proyecto/Views/bebidas/Delete.cshtml
@model Proyecto.Models.bebidas

@{
    ViewBag.Title = "Delete";
}

<h2>Borrar</h2>

<h3>¿Estas seguro que deseas borrar esta bebida?</h3>
<div> 
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.usuario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.usuario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.foto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.foto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ingredientes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ingredientes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.preparacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.preparacion)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Borrar" class="btn btn-default" /> &nbsp;
            @Html.ActionLink("Volver a la lista", "Index", null, new { @class = "btn btn-primary" })
        </div>
    }
</div>

Proyecto/Proyecto/Views/bebidas/Details.cshtml
@model Proyecto.Models.bebidas 

@{
    ViewBag.Title = "Details";
}

<h2>Preparacion</h2>

<div>
    <hr />
     <div class="row">
         <div class="col-md-1"></div>
             <div class="col-md-10">
                 <div class="jumbotron" style="text-align:center;">
                     <p>Nombre: @Html.DisplayFor(model => model.nombre)</p><br />
                     <img src='~/Fotos/@Model.foto' style="height:auto; width:auto;" class="img-thumbnail" /><br /><br />
                     <p>Creado por: @Html.DisplayFor(model => model.usuario)</p><br />
                     <p style="text-align:justify;">Ingredientes: @Html.DisplayFor(model => model.ingredientes)</p><br />
                     <p style="text-align:justify;">Preparacion: @Html.DisplayFor(model => model.preparacion)</p><br />
                 </div>
             </div>
         <div class="col-md-1"></div> 
         </div>
</div>
<p> 
    @Html.ActionLink("Volver a la lista", "Index",null, new { @class = "btn btn-primary" })
</p>

Proyecto/Proyecto/Views/bebidas/Edit.cshtml
@model Proyecto.Models.bebidas

@{
    ViewBag.Title = "Edit";
}

<h2>Editar</h2>

@using (Html.BeginForm("FileUploadUpdate", "bebidas", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
    @Html.AntiForgeryToken()

    <div class="form-horizontal"> 
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.idbebida)

        <div class="form-group">
            @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.usuario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.usuario, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.usuario, "", new { @class = "text-danger" })
            </div>
        </div> 

        <div class="form-group">
            @Html.LabelFor(model => model.foto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="file" id="file" style="width: 100%;" /> <br />
                @Html.ValidationMessageFor(model => model.foto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ingredientes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ingredientes, new { htmlAttributes = new { @class = "form-control", rows = "6" } })
                @Html.ValidationMessageFor(model => model.ingredientes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.preparacion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.preparacion, new { htmlAttributes = new { @class = "form-control", rows = "6" } })
                @Html.ValidationMessageFor(model => model.preparacion, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver a la lista", "Index", null, new { @class = "btn btn-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Proyecto/Proyecto/Views/bebidas/Index.cshtml
@using PagedList
@using PagedList.Mvc
@model IPagedList<Proyecto.Models.bebidas>

@{
    ViewBag.Title = "Bebidas";
    int i = 1;
}
<h3>¿Buscas algo nuevo?</h3>
<h4>Prueba las bebidas creadas por la comunidad</h4><br />
<table class="table">

    @foreach (var item in Model)
    {
        <div class="col-md-3 well" style="text-align:center;">
            <h4>@Html.DisplayFor(modelItem => item.nombre)</h4>
            <img src="../Fotos/@item.foto" width="200" height="200" class="img-rounded" /> <br /><br />
            <p>Creado por:@Html.DisplayFor(modelItem => item.usuario)</p>
            @Html.ActionLink("Preparar", "Details", new { id = item.idbebida }, new { @class = "btn btn-success" })
        </div>
        if (i == 10) { break; }
        else { i++; }
    }
</table> 
<div class="pagedList">
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page }), PagedListRenderOptions.ClassicPlusFirstAndLast)
</div>
 

Proyecto/Proyecto/Views/bebidas/buscarbebida.cshtml
@model IEnumerable<Proyecto.Models.bebidas>

@{
    ViewBag.Title = "Resultado de busqueda";
    int i = 1;
}

<h2>Resultados de busqueda</h2><br /> 
<table class="table">
    @foreach (var item in Model)
    { 
        <div class="col-md-3 well">
            <center><h4>@Html.DisplayFor(modelItem => item.nombre)</h4></center>
            <center><img src="../Fotos/@item.foto" width="200" height="200" class="img-rounded" /></center>
            <center>
                <br /><br />
                @Html.ActionLink("Preparar", "Details", new { id = item.idbebida }, new { @class = "btn btn-success" })
            </center>
        </div>
        if (i == 10) { break; }
        else { i++; }
    }
    </table> 

Proyecto/Proyecto/Views/bebidas/misbebidas.cshtml
 
@model IEnumerable<Proyecto.Models.bebidas> 

@{
    ViewBag.Title = "Mis Bebidas";
    int i = 1;
}

<h2>Mis Bebidas</h2>

<p>
    @Html.ActionLink("Crea un nuevo trago", "Create", null, new { @class = "btn btn-info" })
</p>
<table class="table">
    @foreach (var item in Model)
    {
        if (item.usuario == User.Identity.Name)
        {
        <div class="col-md-3 well" style="text-align:center;">
            <h4>@Html.DisplayFor(modelItem => item.nombre)</h4>
            <img src="../Fotos/@item.foto" width="200" height="200" class="img-rounded" /> <br /><br />
            <p>Creado por:@Html.DisplayFor(modelItem => item.usuario)</p> 
            @Html.ActionLink("Editar", "Edit", new { id = item.idbebida }, new { @class = "btn btn-primary" }) 
            @Html.ActionLink("Preparar", "Details", new { id = item.idbebida }, new { @class = "btn btn-success" }) 
            @Html.ActionLink("Borrar", "Delete", new { id = item.idbebida }, new { @class = "btn btn-danger" })
        </div>
            if (i == 10) { break; }
            else { i++; }
        }
    }
</table> 
 